apiVersion: deploy.toolkit/v1
kind: Environment

metadata:
  name: production

spec:
  release: .deploy/releases/my-app-0.1.0.yaml

  target: production-primary

  failurePolicy:
    autoRollback: safe-only
